---
title: "Chapter 13"
author: "Scott Spencer"
date: "9/1/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, message = FALSE, error = FALSE)
library(dplyr); library(tidyr); library(rstan); library(skimr); library(ggplot2); library(ggthemes)
```


## 13.1 Varying slopes by construction

### 13.1.1 simulate the population

Simulate data

```{r}
a <- 3.5
b <- (-1)
sigma_a <- 1
sigma_b <- 0.5
rho <- (-0.7)
Mu <- c(a, b)
cov_ab <- sigma_a * sigma_b * rho
```

Setup the covariance matrix

```{r}
# approach 1
Sigma <- matrix( c(sigma_a^2, cov_ab, cov_ab, sigma_b^2), ncol = 2 )

# approach 2
sigmas <- c(sigma_a, sigma_b)
Rho <- matrix(c(1, rho, rho, 1), nrow = 2)
Sigma <- diag(sigmas) %*% Rho %*% diag(sigmas)

```

simulate cafes

```{r}
N_cafes <- 20
library(MASS)
set.seed(5)
vary_effects <- mvrnorm(N_cafes, Mu, Sigma)
```

separate the intercepts and slopes

```{r}
a_cafe <- vary_effects[,1]
b_cafe <- vary_effects[,2]
```


```{r}
ggplot() + theme_tufte(base_family = 'sans') +
  geom_point(aes(a_cafes, b_cafes), shape = 21, color = 'dodgerblue') +
  stat_ellipse(aes(a_cafes, b_cafes), level = .50, alpha = .1) +
  stat_ellipse(aes(a_cafes, b_cafes), level = .89, alpha = .1) +
  stat_ellipse(aes(a_cafes, b_cafes), level = .97, alpha = .1) +
  labs(x = 'intercepts (a_cafes)', y = 'slopes (b_cafes)')
```

### 13.1.2 simulate observations

```{r}
N_visits <- 10
afternoon <- rep(0:1, N_visits * N_cafes / 2)
cafe_id <- rep(1:N_cafes, each = N_visits)
mu <- a_cafe[cafe_id] + b_cafe[cafe_id] * afternoon
sigma <- 0.5
wait <- rnorm(N_visits * N_cafes, mu, sigma)
d <- data.frame(cafe = cafe_id, afternoon = afternoon, wait = wait)
```

### 13.1.3 the varying slopes model

Code a model in Stan.

```{stan output.var="m13_1"}
data {
  int N;
  int N_cafe;
  int cafe_id[N];
  real W[N];
  int A[N];
}
parameters {
  real a;
  real b;
  vector[N_cafe] a_cafe;
  vector[N_cafe] b_cafe;
  real<lower=0> sigma;
  vector<lower=0>[2] sigma_cafe;
  corr_matrix[2] Rho;
}
transformed parameters {
  vector[2] Mu_ab = [a, b]';
  vector[2] v_a_cafeb_cafe[N_cafe];
  cov_matrix[2] SRS_sigma_cafeRho;
  for ( j in 1:N_cafe ) v_a_cafeb_cafe[j,1:2] = [a_cafe[j], b_cafe[j]]';
  SRS_sigma_cafeRho = quad_form_diag(Rho,sigma_cafe);
}
model {
  vector[N] mu;
  
  //priors
  target += normal_lpdf(a | 0, 10);
  target += normal_lpdf(b | 0, 10);
  target += cauchy_lpdf(sigma | 0 , 2 );
  target += cauchy_lpdf(sigma_cafe | 0 , 2 );
  target += lkj_corr_lpdf(Rho | 2 );
  
  // linear model  
  for(i in 1:N) mu[i] = a_cafe[cafe_id[i]] + b_cafe[cafe_id[i]] * A[i];
  
  target += normal_lpdf(W | mu, sigma);
  target += multi_normal_lpdf(v_a_cafeb_cafe | Mu_ab , SRS_sigma_cafeRho );
}
generated quantities {
  vector[N] log_lik;
  {
  vector[N] mu;
  for(i in 1:N) {
    mu[i] = a_cafe[cafe_id[i]] + b_cafe[cafe_id[i]] * A[i];
    log_lik[i] = normal_lpdf(W[i] | mu[i], sigma);
  }
  }
}
```

Organize data and sample from model.

```{r}
dat <- list(
  N = NROW(d),
  N_cafe = max(d$cafe),
  cafe_id = d$cafe,
  W = d$wait,
  A = d$afternoon
)

fit13_1 <- sampling(m13_1, data = dat, iter = 5000, chains = 2, cores = 2)
```

```{r}
print(fit13_1, include = F, pars = 'log_lik', probs = c(.1, .5, .9))
```

Examine correlation.

```{r}
rho_prior <- rethinking::rlkjcorr(5000, 2, 2)

post13_1 <- as.data.frame(fit13_1)

ggplot(post13_1) + theme_tufte(base_family = 'sans') +
  geom_density(aes(x = `Rho[1,2]`), color = 'dodgerblue') +
  geom_density(aes(x = rho_prior[, 1, 2]), linetype = 'dashed') +
  annotate('text', x=0.2, y = .75, label = 'prior') +
  annotate('text', x=0, y = 1.2, label = 'posterior', color = 'dodgerblue') +
  labs(x = 'correlation')
```

Compare regularized varying effects to unpooled estimates.

```{r}
# calculate unpooled estimates from the data
a1 <- sapply(1:N_cafes, function(i) mean(wait[cafe_id == i & afternoon == 0]))
b1 <- sapply(1:N_cafes, function(i) mean(wait[cafe_id == i & afternoon == 1])) - a1

# extract posterior means from partially pooled estimates
a2 <- apply(post13_1[,grep('^a_cafe', colnames(post13_1))], 2, mean)
b2 <- apply(post13_1[,grep('^b_cafe', colnames(post13_1))], 2, mean)

df <- data.frame(a1, b1, a2, b2)

# plot both
ggplot(df) + theme_tufte(base_family = 'sans') +
  stat_ellipse(aes(x = a1, y = b1), level = .1, alpha = .2) +
  stat_ellipse(aes(x = a1, y = b1), level = .3, alpha = .2) +
  stat_ellipse(aes(x = a1, y = b1), level = .5, alpha = .2) +
  stat_ellipse(aes(x = a1, y = b1), level = .8, alpha = .2) +
  stat_ellipse(aes(x = a1, y = b1), level = .99, alpha = .2) +
  geom_point(aes(x = a1, y = b1), color = 'dodgerblue') +
  geom_point(aes(x = a2, y = b2), shape = 21) +
  geom_segment(aes(x = a1, xend = a2, y = b1, yend = b2)) +
  labs(x = 'intercept', y = 'slope')
```




